### ISSUE TITLE
Required form fields are missing correct semantics

### ISSUE THREAD

**Issue by timdujardin** [ioulian/next-ui-ghent-app-starter#15]
- In Label.tsx, the asterisk can be aria-hidden="true" without aria-label or title attribute.
- In FormField.tsx, the required attribute is missing on the Children rendering.

```
{Children.map(children, (child) =>
              isValidElement(child)
                ? cloneElement(child, {
                    ...child.props,
                    ...registerProps,
                    name,
  -->               required: !!options?.required,
                    ...sharedProps,
                  })
                : /* c8 ignore next */
                  null,
            )}
```

The required attribute on the form element that is correctly associated with the label element will make sure that "Required" is also communicated correctly.

**Comment by ioulian** [comment]
b80cad463f3f7cce359954e399a9d7ce8110fb08
