### ISSUE TITLE
PasswordInput accessibility issues/considerations

### ISSUE THREAD

**Issue by timdujardin** [ioulian/next-ui-ghent-app-starter#16]
## Password strength

PasswordInput needs aria-live to communicate password strength status
You can refer to this example: https://www.w3.org/WAI/tutorials/forms/examples/password/.

## Repeat password field

The repeat password field in the example is something to reconsider, if you ask for filling in the same value in multiple fields there could be a cognitive overload for some users.

> People with impaired short-term memory may be unable to recall passwords or copy access codes. They may have trouble or be unable to remember new icons and interface paradigms.

> People with impaired working memory may only be able to hold one to three items in their memory at the same time. This can make it difficult to hold information temporarily or copy access codes.

https://www.w3.org/TR/coga-usable/#:~:text=People%20with%20impaired%20short%2Dterm,temporarily%20or%20copy%20access%20codes.

**Comment by ioulian** [comment]
strength meter added in de3a07a89a54a9a656387956c3f1242c00418a0a . Password repeat should be handled per project basis
